sequenceDiagram
    participant browser
    participant server

    browser->>server: GET spa
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET /main.css
    activate server
    server-->>browser: CSS file
    deactivate server

    browser->>server: GET /spa.js
    activate server
    server-->>browser: JavaScript file
    deactivate server

    Note right of browser: The browser executes the JavaScript code

    browser->>server: GET data.json
    activate server
    server-->>browser: JSON data
    deactivate server

    Note right of browser: The browser dynamically updates the page content using the received data
